#localhost
:http = http
:host = 127.0.0.1:3000

#test connection
GET :http://:host/
Content-Type: application/json
{"name":"daniel"}


#post
POST :http://:host/
Content-Type: application/json
{"name":"daniel"}


#post
DELETE :http://:host/
Content-Type: application/json
{"name":"daniel"}




#get user by id
GET :http://:host/users/5
Content-Type: application/json
{}


# post user
POST :http://:host/users
Content-Type: application/json
{"text": "daniel"}
